### ISSUE TITLE
Create some sort of system to account for concurrent editing of pages

### ISSUE THREAD

**Issue by thefearlesscoder** [als-computing/splash-client#75]
Currently if two users edit a document at the same time this could lead to some nasty behavior. We need to design a method to account for this situation.

@dylanmcreynolds do you have any recommendations?

**Comment by dylanmcreynolds** [comment]
The proper way to handle this in REST I believe is to use Last-Modified and If-Modified-Since headers. A good description is here: https://blog.4psa.com/rest-best-practices-managing-concurrent-updates/

I think that the bulk of this logic would be controlled in the VersionedMongoService GET and UPDATE methods. GET will return last-modified to the caller, UPDATE will control If-Modified-Since. I'm not sure how required etag is here. That needs some research. 

Then I envision that the service will message back to the route endpoints with a new exception for precondition failed, which would translate back the 412 with a message about who who provided the update. 

How does the client respond? Well, we don't want the user to lose changes, but I don't want to build a sophisticated visual differencer. How about responding with something like "Ford Prefect has updated this page since you opened it. Would you like to view their update?". If yes, then open the recent version in a new window, let the user stare and compare for now. If they approve the update again, send it without the If-Modified-Since. Does this work?

**Comment by thefearlesscoder** [comment]
In order to allow concurrent editing of the API we will require that the client first request the document from the server. The person on the frontend will do some editing to that document. The browser client will issue a GET  request, and server will add an Etag header/ Any subsequent PUT or PATCH request from the browser will contain an "If-match: <etag>" header with the server supplied etag. This etag must either be a positive integer, or the string “ignore.” Any other value should return an error back to the client. 
    The server will pass this etag as an optional argument all the way down to the Mongo Versioning Service. 

If the”If-match” header is left out then this service will simply update the document without paying attention to the version number. 
If the argument is a positive integer then it will compare this integer to the current version number:
If the two version numbers are the same then this service will simply update the document and will return a new version etag back to the client.
If the incoming version number is smaller then we should throw an error which will be caught by the router. This error should contain the full document as it exists in the database. The router will catch this error and use it to craft a response for the client. What error code do we use???? 412, precondition failed (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match). And we should put a message about the user and time of the conflicting version in the body of the 412 response.
If the incoming version number is larger, what error do we throw here???????????????? same as above, 412, but with the username and time of the most recent update.
If the client gets a success message we do nothing. If the client gets a failure message then we display a pop out showing the doc in its current form and a list of all users who have edited the doc as well as the times they edited it at. We have some sort of message like: DETECTED NEW DOCUMENT EDITS SINCE YOU LAST OPENED THIS DOCUMENT. Please try to incorporate these edits into your current document as best as you can and then hit save again. The whole save process will be subsequently repeated, except the newest version number will be sent by the client when save is hit. The key here is that the user's changes are not lost. Can we open a new window with the most recent/conflicting change?
